### ISSUE TITLE
Can this library be used to programatically upload/add metadata to images?

### ISSUE THREAD

**Issue by kevinlinxc** [Lumen5/shutterstock-api#23]
I am wondering if I can automate the whole process of uploading, labelling, and selling a stock photo on shutterstock basically

**Comment by dacox** [comment]
> I am wondering if I can automate the whole process of uploading, labelling, and selling a stock photo on shutterstock basically

@kevinlinxc this library is generated from OpenAPI bindings. The short answer is - I don't know, since we have a totally different use case. Perusing the `docs` folder, I believe the answer is "no" .
