### ISSUE TITLE
The library wants an access token... I have a consumer key and secret

### ISSUE THREAD

**Issue by mwiederrecht** [Lumen5/shutterstock-api#9]
Forgive me if this is a newbie question (I admit I am one), but I am getting stuck when trying to use this library because it is asking for an "Access Token", while as far as I can see Shutterstock has given me a "Consumer Key" and "Consumer Secret".  Any help?

**Comment by dacox** [comment]
@mwiederrecht This library makes the assumption that you are using the OAuth authentication flow. Shutterstock explains how to use the info you've been given to generate an OAuth token [here](https://developers.shutterstock.com/documentation/authentication)
Cheers

**Comment by mwiederrecht** [comment]
Ahaaaaa.  Yup, newbie indeed.  Thanks!
